# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://SuperXiaoLan.github.io
date_format: "ordinal"
title: 超级路易
subtitle: "Luigi's graduate learning road"
description: "路易的研究生学习之路"
keywords: blockchain, luigi, xiaolan, crazy blockchainer, Vitalik's follower
timezone: Asia/Shanghai
encoding: "utf-8"
# 页面左下角显示的年份
since: 2022-12-29
# 源码仓库，请替换成自己的
repository: superxiaolan/SuperXiaoLan.github.io

# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: false
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: false
        hide-platforms: qq,facebook
    # 不蒜子访问统计
    busuanzi:
        enabled: false
        start_date: 2022-12-29
    # My Popular Repositories
    side_bar_repo:
        enabled: true
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: true
        image_alt: 超级路易
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: cate
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Luigi
organization: 
organization_url: 
github_username: superxiaolan
location: HuNan, China
email: awilliegutierres@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

#   -
#     href: /open-source/
#     label: 开源

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar, giscus
comments_provider: giscus
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# disqus 配置参考：https://disqus.com
disqus:
    username: 
# gitment 配置参考：https://imsun.net/posts/gitment-introduction/
gitment:
    owner: superxiaolan
    repo: blog-comments
    oauth:
        client_id: 05649853357577ba3e8e
        client_secret: 490693868c8d9697c68563bf86c6de067cd4c528
# gitalk 配置参考：https://github.com/gitalk/gitalk#install
gitalk:
    owner: superxiaolan
    repo: blog-comments
    clientID: 05649853357577ba3e8e
    clientSecret: 490693868c8d9697c68563bf86c6de067cd4c528
# utterances 配置参考：https://utteranc.es/
utterances:
    repo: superxiaolan/blog-comments
# beaudar 配置参考：https://beaudar.lipk.org/
beaudar:
    repo: superxiaolan/blog-comments
# giscus 配置参考：https://giscus.app/zh-CN
giscus:
    repo: superxiaolan/blog-comments
    repo-id: R_kgDOIsUlIw
    category: Announcements
    category-id: DIC_kwDOIsUlI84CTUBb
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-38676921-4
    adsense:
        footer: true
        sidebar: true 
        sidebar-detail: true 
        content_header: false
        content_footer: false
